#!/bin/bash

cd ~/bin/dw-timer/

if test -f curr-DWS.tmp; then
	date +"%Y-%m-%d %H:%M:%S" >> curr-DWS.tmp
	echo ''
	python -c "from src import *; user_input()"
	echo ""
	echo "Current session ended"
	echo "Time spent working:"
	python -c "from src import *; print('>>', work_time('curr-DWS.tmp'), 'min <<', f'  ({work_today()} min today)')"
	echo "Good job!"
	echo ""
	rm curr-DWS.tmp
else
	echo ""
	echo "Session isn't yet started!" 
	echo ""
fi

cd - > /dev/null
