#!/bin/bash

t(){
	date +"%Y-%m-%d %H:%M:%S"
}

cd ~/bin/dw-timer/

if test -f curr-DWS.tmp; then
	echo ""
	echo "Current session is already running!"
	echo ""
else
	t > curr-DWS.tmp
	echo ""
	echo Deep Work Session started at: 
	t
	echo ""
fi

cd - > /dev/null
